//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-ja.js
// Module:    /manager/multiphp_manager/index.cmb-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] バージョン “[_1]” を[numerate,_2,ドメイン,複数のドメイン]に適用できませんでした。","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] のバージョン “[_1]” を、選択された[numerate,_2,ドメイン,ドメイン]に適用できませんでした。","For more information, check the error message at the top of the page.":"詳細については、ページの一番上のエラー メッセージを確認してください。","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] バージョン “[_1]” が[numerate,_2,ドメイン,複数のドメイン]に正常に適用されました。","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] バージョン “[_1]” が、選択された[numerate,_2,ドメイン,ドメイン]に正常に適用されました。","System Default":"システムの既定値","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
