//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-ar.js
// Module:    /manager/multiphp_manager/index.cmb-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"فشل تطبيق الإصدار [asis,PHP] “[_1]” إلى [numerate,_2,مجال,بعض المجالات].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"فشل تطبيق الإصدار [asis,PHP] “[_1]” على [numerate,_2,المجال,المجالات] المحدد.","For more information, check the error message at the top of the page.":"لمزيد من المعلومات، تحقق من رسالة الخطأ أعلى الصفحة.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"تم تطبيق الإصدار [asis,PHP] “[_1]” على [numerate,_2,مجال,بعض المجالات] بنجاح.","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"تم تطبيق إصدار [asis,PHP] بنجاح “[_1]” إلى [numerate,_2,المجال,المجالات] المحدد.","System Default":"إعداد افتراضي للنظام","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
