//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-ko.js
// Module:    /manager/multiphp_manager/index.cmb-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] 버전 “[_1]”을(를) [numerate,_2,도메인,일부 도메인]에 적용하지 못했습니다.","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] 버전 “[_1]”을(를) 선택한 [numerate,_2,도메인,도메인]에 적용하지 못했습니다.","For more information, check the error message at the top of the page.":"For more information, check the error message at the top of the page.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] 버전 “[_1]”을(를) [numerate,_2,도메인,일부 도메인]에 성공적으로 적용했습니다.","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] 버전 “[_1]”을(를) 선택한 [numerate,_2,도메인,도메인]에 적용했습니다.","System Default":"시스템 기본값","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
