//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-fr.js
// Module:    /manager/multiphp_manager/index.cmb-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Impossible d’appliquer la version « [_1] » de [asis,PHP] à [numerate,_2,un domaine,plusieurs domaines].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Impossible d’appliquer la version [asis,PHP] « [_1] » au(x) [numerate,_2,le domaine correspondant,les domaines correspondants] sélectionné(s).","For more information, check the error message at the top of the page.":"Consultez le message d’erreur en haut de la page pour en savoir plus.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"La version [asis,PHP] « [_1] » a été appliquée à[numerate,_2,un domaine,plusieurs domaines].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"La version [asis,PHP] « [_1] » a été appliquée au(x) [numerate,_2,le domaine correspondant,les domaines correspondants].","System Default":"Valeur par défaut du système","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
