//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-de.js
// Module:    /manager/multiphp_manager/index.cmb-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP]-Version „[_1]“ konnte auf [numerate,_2,eine Domäne,einige Domänen] nicht angewendet werden.","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP]-Version „[_1]“ konnte nicht auf die ausgewählte/n [numerate,_2,Domäne,Domänen] angewendet werden.","For more information, check the error message at the top of the page.":"Weitere Informationen finden Sie in der Fehlermeldung oben auf der Seite.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP]-Version „[_1]“ erfolgreich auf [numerate,_2,eine Domäne,einige Domänen] angewendet.","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP]-Version „[_1]“ wurde erfolgreich auf die ausgewählte/n [numerate,_2,Domäne,Domänen] angewendet.","System Default":"Systemstandardeinstellung","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
