//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-sv.js
// Module:    /manager/multiphp_manager/index.cmb-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Det gick inte att tillämpa [asis,PHP] version ”[_1]” på [numerate,_2,en domän,vissa domäner].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Det gick inte att tillämpa [asis,PHP] version ”[_1]” på de valda [numerate,_2,domän,domäner].","For more information, check the error message at the top of the page.":"For more information, check the error message at the top of the page.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] version ”[_1]” har tillämpats på [numerate,_2,en domän,vissa domäner].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] version ”[_1]” har lagts till på valda [numerate,_2,domän,domäner].","System Default":"Systemstandard","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
