//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/index.cmb-zh.js
// Module:    /manager/multiphp_manager/index.cmb-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"未能将 [asis,PHP] 版本“[_1]”应用到[numerate,_2,一个域,一些域]。","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"未能将 [asis,PHP] 版本“[_1]”应用到所选[numerate,_2,域,域]。","For more information, check the error message at the top of the page.":"有关更多信息，请查看页面顶部的错误消息。","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"已成功将 [asis,PHP] 版本“[_1]”应用到[numerate,_2,一个域,一些域]。","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"已成功将 [asis,PHP] 版本“[_1]”应用到所选[numerate,_2,域,域]。","System Default":"系统默认设置","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
