//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/views/listEmailAccounts.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/views/listEmailAccounts-zh_tw.js
// Module:    /manager/mail/pops/views/listEmailAccounts-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” deleted.":"Account “[_1]” deleted.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"顯示 [_3] 筆記錄中的 [_1] 到 [_2]","Password for “[_1]” has been changed.":"“[_1]”的密碼已變更。","[_1]%":"[_1]%"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
