//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb-nl.js
// Module:    /manager/multiphp_ini_editor/index.cmb-nl
// Locale:    nl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Disabled":"Uitgeschakeld","Enabled":"Ingeschakeld","Errors occurred while retrieving the [asis,PHP INI] locations.":"Er zijn fouten opgetreden bij het ophalen van de [asis,PHP INI]-locaties.","Successfully applied the settings.":"De instellingen zijn toegepast.","Successfully saved the changes.":"De wijzigingen zijn opgeslagen.","The [asis,INI] content does not exist. You may add new content.":"De [asis,INI]-inhoud bestaat niet. U kunt nieuwe inhoud toevoegen.","You must click ‘[_1]’ to apply the new changes.":"U moet op ‘[_1]’ klikken om de nieuwe wijzigingen toe te passen.","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP] Standaard: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Niet beschikbaar --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Selecteer een locatie --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
