//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb-bg.js
// Module:    /manager/multiphp_ini_editor/index.cmb-bg
// Locale:    bg
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Disabled":"Disabled","Enabled":"Enabled","Errors occurred while retrieving the [asis,PHP INI] locations.":"Errors occurred while retrieving the [asis,PHP INI] locations.","Successfully applied the settings.":"Successfully applied the settings.","Successfully saved the changes.":"Successfully saved the changes.","The [asis,INI] content does not exist. You may add new content.":"The [asis,INI] content does not exist. You may add new content.","You must click ‘[_1]’ to apply the new changes.":"You must click ‘[_1]’ to apply the new changes.","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP] Default: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
