//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/index.cmb-it.js
// Module:    /manager/multiphp_ini_editor/index.cmb-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Disabled":"Disattivato","Enabled":"Attivato","Errors occurred while retrieving the [asis,PHP INI] locations.":"Si sono verificati errori durante il recupero delle posizioni [asis,PHP INI].","Successfully applied the settings.":"Applicazione delle impostazioni completata.","Successfully saved the changes.":"Salvataggio modifiche completato.","The [asis,INI] content does not exist. You may add new content.":"Contenuto account [asis,INI] inesistente. È possibile aggiungere nuovo contenuto.","You must click ‘[_1]’ to apply the new changes.":"È necessario fare clic su ‘[_1]’ per applicare le nuove modifiche.","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP] predefinito: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Non disponibile --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Selezionare una posizione --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
