//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-fil.js
// Module:    /manager/mail/pops/index.cmb-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Allow “[_1]” to log in and to receive mail.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"Ipinapakita ang [_1] hanggang [_2] sa [_3] (na) record","Password for “[_1]” has been changed.":"Ang password para sa “[_1]” ay binago.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Suspend","Suspend “[_1]”’s logins and incoming mail.":"Suspend “[_1]”’s logins and incoming mail.","Unsuspend":"Unsuspend","[_1]%":"[_1]%","“[_1]” can receive mail.":"“[_1]” can receive mail.","“[_1]” can send and receive mail.":"“[_1]” can send and receive mail.","“[_1]” is suspended from receiving mail.":"“[_1]” is suspended from receiving mail.","“[_1]” is suspended from sending and reading mail.":"“[_1]” is suspended from sending and reading mail."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
