//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-zh.js
// Module:    /manager/mail/pops/index.cmb-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"允许“[_1]”登录并接收邮件。","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"正在显示 [_1] 至 [_2]，共 [_3] 个记录","Password for “[_1]” has been changed.":"“[_1]”的密码已更改。","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"暂停","Suspend “[_1]”’s logins and incoming mail.":"暂停“[_1]”的登录名和接收邮件。","Unsuspend":"取消暂停","[_1]%":"[_1]%","“[_1]” can receive mail.":"“[_1]”可以接收邮件。","“[_1]” can send and receive mail.":"“[_1]”可以发送和接收邮件。","“[_1]” is suspended from receiving mail.":"已暂停“[_1]”接收邮件。","“[_1]” is suspended from sending and reading mail.":"已暂停“[_1]”发送和阅读邮件。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
