//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-ja.js
// Module:    /manager/mail/pops/index.cmb-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"“[_1]” に、ログインおよびメール受信を許可します。","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"[_3] レコードのうち [_1] ～ [_2] を表示しています","Password for “[_1]” has been changed.":"“[_1]” のパスワードが変更されました。","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"一時停止","Suspend “[_1]”’s logins and incoming mail.":"[_1] のログインと受信メールを一時停止","Unsuspend":"一時停止を解除","[_1]%":"[_1]%","“[_1]” can receive mail.":"“[_1]” は電子メールを受信できます。","“[_1]” can send and receive mail.":"“[_1]” は電子メールの送信および受信ができます。","“[_1]” is suspended from receiving mail.":"“[_1]” によるメール受信を一時停止します。","“[_1]” is suspended from sending and reading mail.":"送信メールと受信メールから “[_1]” が一時停止されました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
