//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-tr.js
// Module:    /manager/mail/pops/index.cmb-tr
// Locale:    tr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"“[_1]” öğesinin oturum açmasına ve posta almasına izin ver.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"[_3] kayıttan [_1] ila [_2] arası görüntüleniyor","Password for “[_1]” has been changed.":"“[_1]” şifresi değiştirildi.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Askıya al","Suspend “[_1]”’s logins and incoming mail.":"“[_1]” öğesinin oturum açma işlemlerini ve gelen postasını askıya alın.","Unsuspend":"Askıya Almayı Kaldırma","[_1]%":"[_1]%","“[_1]” can receive mail.":"“[_1]” posta alabilir.","“[_1]” can send and receive mail.":"“[_1]” posta gönderip alabilir.","“[_1]” is suspended from receiving mail.":"“[_1]” kullanıcısının posta alması durduruldu.","“[_1]” is suspended from sending and reading mail.":"“[_1]”, posta göndermekten ve okumaktan menedildi."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
