//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-ru.js
// Module:    /manager/mail/pops/index.cmb-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Разрешите «[_1]» вход и получение почты.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"Показано [_1]–[_2] из [_3] записей","Password for “[_1]” has been changed.":"Пароль для «[_1]» был изменен.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Приостановить","Suspend “[_1]”’s logins and incoming mail.":"Приостановить вход «[_1]» и входящую почту.","Unsuspend":"Отменить приостановку","[_1]%":"[_1]%","“[_1]” can receive mail.":"«[_1]» может получать сообщения электронной почты.","“[_1]” can send and receive mail.":"«[_1]» может отправлять и получать сообщения электронной почты.","“[_1]” is suspended from receiving mail.":"Получение почты для «[_1]» приостановлено.","“[_1]” is suspended from sending and reading mail.":"«[_1]» не разрешено отправлять и читать почту."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
