//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-fr.js
// Module:    /manager/mail/pops/index.cmb-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Autorisez « [_1] » à se connecter et à recevoir des e-mails.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"Affichage des enregistrements [_1] à [_2] sur [_3]","Password for “[_1]” has been changed.":"Le mot de passe de « [_1] » a changé.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Suspendre","Suspend “[_1]”’s logins and incoming mail.":"Suspendez les e-mails entrants et les connexions de [_1].","Unsuspend":"Annuler la suspension","[_1]%":"[_1]%","“[_1]” can receive mail.":"« [_1] » peut recevoir des e-mails.","“[_1]” can send and receive mail.":"« [_1] » peut envoyer et recevoir des e-mails.","“[_1]” is suspended from receiving mail.":"La réception d’e-mails est suspendue pour « [_1] ».","“[_1]” is suspended from sending and reading mail.":"L’envoi et la lecture d’e-mails sont suspendus pour « [_1] »."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
