//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-de.js
// Module:    /manager/mail/pops/index.cmb-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Lassen Sie die Anmeldung und den Empfang von E-Mails durch „[_1]“ zu.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"[_1] bis [_2] von [_3] Datensätzen werden angezeigt.","Password for “[_1]” has been changed.":"Das Kennwort für „[_1]“ wurde geändert.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Sperren","Suspend “[_1]”’s logins and incoming mail.":"Sperren Sie die Anmeldungen und eingehenden E-Mails von „[_1]“.","Unsuspend":"Sperrung aufheben","[_1]%":"[_1]%","“[_1]” can receive mail.":"„[_1]“ kann E-Mail empfangen.","“[_1]” can send and receive mail.":"„[_1]“ kann E-Mail senden und empfangen.","“[_1]” is suspended from receiving mail.":"Der E-Mail-Empfang durch „[_1]“ ist gesperrt.","“[_1]” is suspended from sending and reading mail.":"„[_1]“ ist vom Senden und Lesen von E-Mail gesperrt."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
