//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-ar.js
// Module:    /manager/mail/pops/index.cmb-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"السماح لـ “[_1]” بتسجيل الدخول وتلقي رسالة البريد.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"عرض [_1] إلى [_2] من سجلات [_3]","Password for “[_1]” has been changed.":"تم تغيير كلمة مرور‎ “[_1]‎”.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"إيقاف مؤقت","Suspend “[_1]”’s logins and incoming mail.":"إيقاف عمليات تسجيل دخول “[_1]” والبريد الوارد مؤقتًا.","Unsuspend":"إلغاء الإيقاف المؤقت","[_1]%":"[_1]%","“[_1]” can receive mail.":"يمكن لـ “[_1]” تلقي البريد الإلكتروني.","“[_1]” can send and receive mail.":"يمكن لـ “[_1]” إرسال البريد الإلكتروني وتلقيه.","“[_1]” is suspended from receiving mail.":"تم تعليق “[_1]” من تلقي البريد الإلكتروني.","“[_1]” is suspended from sending and reading mail.":"تم تعليق “[_1]” من إرسال رسائل البريد الإلكتروني وقراءتها."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
