//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-it.js
// Module:    /manager/mail/pops/index.cmb-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Consenti a “[_1]” di eseguire l’accesso e di ricevere posta.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"Visualizzazione dei record da [_1] a [_2] su [_3] record","Password for “[_1]” has been changed.":"Password per “[_1]” modificata.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Sospendi","Suspend “[_1]”’s logins and incoming mail.":"Sospendi accessi “[_1]” e posta in entrata.","Unsuspend":"Annulla sospensione","[_1]%":"[_1]%","“[_1]” can receive mail.":"“[_1]” può ricevere posta.","“[_1]” can send and receive mail.":"“[_1]” può inviare e ricevere posta.","“[_1]” is suspended from receiving mail.":"“[_1]” sospeso dalla ricezione di posta.","“[_1]” is suspended from sending and reading mail.":"“[_1]” è sospeso dall’invio e dalla lettura della posta."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
