//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/manager/mail/pops/index.cmb-fi.js
// Module:    /manager/mail/pops/index.cmb-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” created.":"Account “[_1]” created.","Account “[_1]” deleted.":"Account “[_1]” deleted.","Allow “[_1]” to log in and to receive mail.":"Anna käyttäjän ”[_1]” kirjautua sisään ja vastaanottaa postia.","Changed Quota for “[_1]” to [numf,_2] MB.":"Changed Quota for “[_1]” to [numf,_2] MB.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"Näytetään [_1]–[_2] [_3] tietueesta","Password for “[_1]” has been changed.":"Kohteen [_1] salasana on vaihdettu.","Shared address book disabled.":"Shared address book disabled.","Shared address book enabled.":"Shared address book enabled.","Suspend":"Jäädytä","Suspend “[_1]”’s logins and incoming mail.":"Jäädytä käyttäjän ”[_1]” kirjautumiset ja saapuva posti.","Unsuspend":"Poista jäädytys","[_1]%":"[_1]%","“[_1]” can receive mail.":"”[_1]” voi vastaanottaa postia.","“[_1]” can send and receive mail.":"”[_1]” voi lähettää ja vastaanottaa postia.","“[_1]” is suspended from receiving mail.":"”[_1]” on jäädytetty vastaanottamasta sähköpostia.","“[_1]” is suspended from sending and reading mail.":"”[_1]” on jäädytetty eikä voi lähettää tai lukea posteja."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
