//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/views/basicMode.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/views/basicMode-es_es.js
// Module:    /manager/multiphp_ini_editor/views/basicMode-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Disabled":"Deshabilitado","Enabled":"Habilitado","Errors occurred while retrieving the [asis,PHP INI] locations.":"Han habido errores al recuperar las ubicaciones de [asis,PHP INI].","Successfully applied the settings.":"Se han aplicado correctamente las configuraciones.","You must click ‘[_1]’ to apply the new changes.":"Debe hacer clic en ‘[_1]’ para aplicar los nuevos cambios.","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP] predeterminado: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]- No disponible -[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]- Seleccionar una ubicación -[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
