//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/views/basicMode.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_ini_editor/views/basicMode-de.js
// Module:    /manager/multiphp_ini_editor/views/basicMode-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Disabled":"Deaktiviert","Enabled":"Aktiviert","Errors occurred while retrieving the [asis,PHP INI] locations.":"Beim Abrufen der [asis,PHP INI]-Speicherorte sind Fehler aufgetreten.","Successfully applied the settings.":"Die Einstellungen wurden erfolgreich angewendet.","You must click ‘[_1]’ to apply the new changes.":"Sie müssen auf „[_1]“ klicken, um die neuen Änderungen zu übernehmen.","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP]-Standard: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Nicht verfügbar --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Wählen Sie einen Speicherort aus --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
