//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-es_es.js
// Module:    /manager/multiphp_manager/views/config-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Error al aplicar la versión de [asis,PHP] “[_1]” a [numerate,_2,un dominio,varios dominios].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Error al aplicar la versión de [asis,PHP] “[_1]” [numerate,_2,el dominio coincidente,los dominios coincidentes].","For more information, check the error message at the top of the page.":"Para obtener más información, compruebe el mensaje de error que aparece en la parte superior de la página.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Se ha aplicado correctamente la versión de [asis,PHP] “[_1]” a [numerate,_2,un dominio,varios dominios].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Se ha aplicado correctamente la versión de [asis,PHP] “[_1]” a [numerate,_2,el dominio coincidente,los dominios coincidentes] seleccionado(s).","System Default":"Predeterminada del sistema","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
