//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-tr.js
// Module:    /manager/multiphp_manager/views/config-tr
// Locale:    tr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] “[_1]” sürümü [numerate,_2,bir etki alanı,bazı etki alanları]na uygulanamadı.","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] “[_1]” sürümü seçili [numerate,_2,etki alanı,etki alanları]na uygulanamadı.","For more information, check the error message at the top of the page.":"Daha fazla bilgi için sayfanın üzerindeki hata mesajını kontrol edin.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"[asis,PHP] sürümü “[_1]” [numerate,_2,bir etki alanı,bazı etki alanları]’e başarıyla uygulandı.","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"[asis,PHP] sürüm “[_1]”, seçili [numerate,_2,etki alanı,etki alanları]’e başarıyla uygulandı.","System Default":"Sistem Varsayılanı","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
