//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-th.js
// Module:    /manager/multiphp_manager/views/config-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"ไม่สามารถปรับใช้ [asis,PHP] เวอร์ชัน “[_1]” เป็น [numerate,_2,โดเมน,บางโดเมน]","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"ไม่สามารถปรับใช้ [asis,PHP] เวอร์ชัน “[_1]” เป็น [numerate,_2,โดเมน,โดเมน] ที่เลือก","For more information, check the error message at the top of the page.":"For more information, check the error message at the top of the page.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"ปรับใช้ [asis,PHP] เวอร์ชัน “[_1]” กับ [numerate,_2,โดเมน,บางโดเมน] ได้สำเร็จ","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"ปรับใช้ [asis,PHP] เวอร์ชัน “[_1]” ใน [numerate,_2,โดเมน,โดเมน] ที่เลือกเรียบร้อยแล้ว","System Default":"ค่าเริ่มต้นของระบบ","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
