//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-ru.js
// Module:    /manager/multiphp_manager/views/config-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Не удалось применить версию [asis,PHP], «[_1]», к [numerate,_2,домену,некоторым доменам].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Не удалось применить версию [asis,PHP], «[_1]», к [numerate,_2,выбранному домену,выбранным доменам].","For more information, check the error message at the top of the page.":"Дополнительные сведения см. в сообщении об ошибке в верхней части страницы.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Версия [asis,PHP] «[_1]» успешно применена к [numerate,_2,домену,некоторым доменам].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Версия [asis,PHP] «[_1]» успешно применена к [numerate,_2,выбранному домену,выбранным доменам].","System Default":"Системные значения по умолчанию","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
