//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-pl.js
// Module:    /manager/multiphp_manager/views/config-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"W [numerate,_2,jednej z domen,pewnych domenach] nie można zastosować języka [asis,PHP] w wersji „[_1]”.","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"W zaznaczonej(-ych) [numerate,_2,domenę,domeny] nie można zastosować języka [asis,PHP] w wersji „[_1]”.","For more information, check the error message at the top of the page.":"Więcej informacji na ten temat można znaleźć w komunikacie o błędzie na górze strony.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Pomyślnie zastosowano język [asis,PHP] w wersji „[_1]” do [numerate,_2,jednej z domen,pewnych domenach].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Pomyślnie zastosowano język [asis,PHP] w wersji „[_1]” w zaznaczonej/-ych [numerate,_2,domenie,domenach].","System Default":"Domyślne ustawienia systemowe","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
