//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config.js
// Generated: /usr/local/cpanel/base/frontend/manager/multiphp_manager/views/config-fil.js
// Module:    /manager/multiphp_manager/views/config-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:":"A change to the “[output,strong,_1]” domain‘s PHP version affects the following domains:","Failed to apply [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Hindi nalapat ang bersyon ng [asis,PHP] na “[_1]” sa [numerate,_2,isang domain,ilang domain].","Failed to apply [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Hindi nalapat ang bersyon ng [asis,PHP] na “[_1]” sa napiling [numerate,_2,domain,(na) domain].","For more information, check the error message at the top of the page.":"For more information, check the error message at the top of the page.","Successfully applied [asis,PHP] version “[_1]” to [numerate,_2,a domain,some domains].":"Matagumpay na nalapat ang [asis,PHP] version “[_1]” sa [numerate,_2,isang domain,ilang domain].","Successfully applied [asis,PHP] version “[_1]” to the selected [numerate,_2,domain,domains].":"Matagumpay na nalapat ang [asis,PHP] version “[_1]” sa napiling [numerate,_2,domain,(na) domain].","System Default":"Default ng System","This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]":"This domain inherits its [asis,PHP] version “[output,em,_1]” from: [output,strong,_2]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
