//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/js2/sql/managehost.js
// Generated: /usr/local/cpanel/base/frontend/manager/js2/sql/managehost-sv.js
// Module:    /manager/js2/sql/managehost-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Remote Database Hosts":"Fjärrdatabasvärdar","The [output,em,Access Host] field must be a valid hostname, for example, [asis,example.com] or [asis,%.example.com].":"Fältet [output,em,Åtkomstvärd] måste vara ett giltigt värdnamn, t.ex. [asis,example.com] eller [asis,%.example.com]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
