//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/js2/sql/managehost.js
// Generated: /usr/local/cpanel/base/frontend/manager/js2/sql/managehost-zh.js
// Module:    /manager/js2/sql/managehost-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Remote Database Hosts":"远程数据库主机","The [output,em,Access Host] field must be a valid hostname, for example, [asis,example.com] or [asis,%.example.com].":"[output,em,访问主机]字段必须是有效的主机名，如 [asis,example.com] 或 [asis,%.example.com]。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
