//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/js2/sql/managehost.js
// Generated: /usr/local/cpanel/base/frontend/manager/js2/sql/managehost-de.js
// Module:    /manager/js2/sql/managehost-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Remote Database Hosts":"Remote-Datenbankhosts","The [output,em,Access Host] field must be a valid hostname, for example, [asis,example.com] or [asis,%.example.com].":"Im Feld [output,em,Zugriffshost] muss ein gültiger Hostname wie z. B. [asis,example.com] oder [asis,%.example.com] angegeben sein."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
