//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/manager/js2/sql/managehost.js
// Generated: /usr/local/cpanel/base/frontend/manager/js2/sql/managehost-th.js
// Module:    /manager/js2/sql/managehost-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Remote Database Hosts":"โฮสต์ฐานข้อมูลระยะไกล","The [output,em,Access Host] field must be a valid hostname, for example, [asis,example.com] or [asis,%.example.com].":"เขตข้อมูล [output,em,โฮสต์การเข้าถึง] ต้องเป็นชื่อโฮสต์ที่ถูกต้อง เช่น [asis,example.com] หรือ [asis,%.example.com]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
